import UsageBarCore

expectEq(Core.version, "0.1.0", "core version")
testPricing()
testClaudeLimits()
testClaudeStatusLine()
testExtraUsage()
testClaudeCost()
testAggregation()
testCodex()
testCredentials()
testMenuBarMetrics()
testProjection()
testModelBreakdown()
testProjects()
testStaleness()
testChatGPTActivity()
testDialRings()
testLimitBarCoding()
testLimitLevel()
finishTests()
